Crdcdh 160 updates
CBIIT/crdc-datahub-ui pull request #164
Opened 2023-10-06 20:28 UTC by mtangmt

This implements the listDataSubmissions page.
The create a submission button is functional enough for us, but pending some backend changes to fulfill the entire requirements.

2023-10-06 21:00 UTC, amattu2 requested changes
I just did a cursory review of the Type definitions, we have some duplicates in the codebase because multiple features were developed simultaneously. Please review and adjust as necessary. There may be other duplicates so please double check for any I missed.

2023-10-06 21:03 UTC, amattu2 commented on src/graphql/listSubmissions.ts
> +// type Submission {
Please confirm if we need these comments for something or if they are an accident.

2023-10-11 21:39 UTC, amattu2 commented
Adding hold-merge label until the organizations list is updated in the BE and implemented in the FE. Feel free to remove when ready.

2023-10-13 19:18 UTC, Alejandro-Vega commented on src/types/Submissions.d.ts
> +type SubmissionHistoryEvent = {
This is the same thing as the line below: `type DataSubmissionHistoryEvent = HistoryBase<SubmissionStatus>;`
See HistoryBase type for more details.

2023-10-13 19:18 UTC, Alejandro-Vega commented on src/types/Submissions.d.ts
> +type HistoryEvent = {
This already exists in src/types/Application.d.ts as: `type HistoryEvent = HistoryBase<ApplicationStatus>;`

2023-10-13 19:18 UTC, Alejandro-Vega commented on src/types/Submissions.d.ts
> +type Applicant = {
This already exists in src/types/Application.d.ts does this have a use for data submissions?

2023-10-16 16:21 UTC, merged