CRDCDH-921 Creating Data View Details dialog
CBIIT/crdc-datahub-ui pull request #429
Opened 2024-07-16 14:34 UTC by Alejandro-Vega

### Overview

Created a dialog that will display more details about nodes in the Data View tab of the Data Submission Dashboard. When the identity column (first column) is clicked, it will open this dialog to show more information as well as the related nodes displayed in table form.

### Change Details (Specifics)

- Added queries/types for `getNodeDetail` and `getRelatedNodes`. Also created `getRelatedNodeProperties` query to get the properties and identity column separately. 
- Updated getSubmissionNodes query to return the `IDPropName`, which I used to always ensure the identity column is first in the data view table.
- Created data view details dialog which consists of information about the node itself, as well as related nodes displayed as tabs. It will show the parent nodes and child nodes as tabs, with the parent nodes being first, as well as the total nodes being displayed.

### Related Ticket(s)

[CRDCDH-921](https://tracker.nci.nih.gov/browse/CRDCDH-921)

2024-07-17 17:09 UTC, amattu2 requested changes
Awesome job. I annotated a few things below, most of which are optional updates, so feel free to dismiss them.

2024-07-17 19:41 UTC, amattu2 commented on src/components/DataSubmissions/DataViewDetails.tsx
> +            <StyledLabel variant="body1">{nodeType} ID</StyledLabel>
Retested and the overlap is fixed.

<img width="562" alt="Screenshot 2024-07-17 at 3 32 38 PM" src="https://github.com/user-attachments/assets/20fc369d-946e-4727-8aa6-92ab034bb85f">

2024-07-18 23:38 UTC, Alejandro-Vega commented on src/graphql/getRelatedNodeProperties.ts
> +  query getRelatedNodeProperties(
Thanks for this suggestion, I added it!

2024-07-18 23:39 UTC, Alejandro-Vega commented on src/components/DataSubmissions/DataViewDetailsDialog.tsx
> +  <StyledDialog open={open} onClose={onClose} title="" scroll="body" {...rest}>
Updated it with some of your help, and made my own adjustments. Had to make some changes due to certain parts breaking. The initial load is still not perfect, but switching tabs is definitely smoother.

2024-07-19 13:28 UTC, amattu2 approved these changes
**Substantially** smoother now. Awesome job!

2024-07-19 13:28 UTC, merged

2024-07-19 13:31 UTC, amattu2 commented
Deleting branches:
- https://github.com/CBIIT/crdc-datahub-ui/tree/CRDCDH-921-temp
- https://github.com/CBIIT/crdc-datahub-ui/tree/amattu2/CRDCDH-921-Fixes