CRDCDH-1995 Validation Results Aggregated/Expanded Table Views
CBIIT/crdc-datahub-ui pull request #557
Opened 2024-12-09 16:52 UTC by Alejandro-Vega

### Overview

N/A

### Change Details (Specifics)

N/A

### Related Ticket(s)

[CRDCDH-2037](https://tracker.nci.nih.gov/browse/CRDCDH-2037) (Aggregated View Task)
[CRDCDH-1995](https://tracker.nci.nih.gov/browse/CRDCDH-1995) (Expanded View Task)
[CRDCDH-1889](https://tracker.nci.nih.gov/browse/CRDCDH-1889) (US)

2025-01-02 20:22 UTC, amattu2 requested changes
I tested it locally as best as I could and annotated a few comments. Feel free to dismiss any.

2025-01-02 22:15 UTC, Alejandro-Vega commented on src/content/dataSubmissions/QualityControl.tsx
>        variables: { id: submissionId },
Agreed, removed in [5dd0da0](https://github.com/CBIIT/crdc-datahub-ui/pull/557/commits/5dd0da01e11edec156676204942643b8377a157c).

2025-01-03 17:58 UTC, Alejandro-Vega commented on src/types/Submissions.d.ts
> +type Issue = {
It was previously called "Issue" on the BE, but it seems it was changed. I updated it in [d7b574b](https://github.com/CBIIT/crdc-datahub-ui/pull/557/commits/d7b574b08967acaa9a90081e983be9917beea7fd) to AggregatedQCResult.

2025-01-06 19:38 UTC, Alejandro-Vega commented on src/components/DataSubmissions/QualityControlFilters.tsx
> +  return (
I totally misread the US requirements. Thanks for catching this, you are right. Aggregated view only has Severity filters, and Expanded view should have all of them. Fixed in [5311349](https://github.com/CBIIT/crdc-datahub-ui/pull/557/commits/53113490bf5c7a59928d1b1243e8fa6eafb0f4c7) and [78403db](https://github.com/CBIIT/crdc-datahub-ui/pull/557/commits/78403db14b1bd30e85083b715519723bc1559671).

2025-01-07 14:21 UTC, Alejandro-Vega commented on src/content/dataSubmissions/QualityControl.tsx
>    const Actions = useMemo<React.ReactNode>(
Updated implementation to support exporting aggregated results while in that that view in [f9ab5c1](https://github.com/CBIIT/crdc-datahub-ui/pull/557/commits/f9ab5c177f10f798b6908179da7d08a7284cebce). Please review.

2025-01-07 14:31 UTC, Alejandro-Vega commented on src/content/dataSubmissions/QualityControl.test.tsx
> +    // expect(mockMatcher).toHaveBeenCalledWith(expect.objectContaining({ severities: "All" }));
Oops, I sometimes add these when I have a stubborn test that keeps failing. I usually return at the end to find the cause, in this case it was just waiting for the mock to be called. Updated in [247179e](https://github.com/CBIIT/crdc-datahub-ui/pull/557/commits/247179e71a13746353f79273237d97ad700bf81c).

2025-01-07 17:21 UTC, amattu2 approved these changes
Changes LGTM!

Everything seems to work, except the type filter and expand button (as noted). Feel free to merge when verified against the finished API.

2025-01-15 22:20 UTC, Alejandro-Vega commented
@amattu2 The BE is now ready and working properly. I also made some slight changes so that the filters reset when toggling the table view in [7bda97e](https://github.com/CBIIT/crdc-datahub-ui/pull/557/commits/7bda97e8c678d0cd736d8d2d8b052d22d224ee31), so please review my changes and check if you find any issues that I couldn't. Otherwise, it seems good to go.

2025-01-16 14:57 UTC, Alejandro-Vega commented
> @Alejandro-Vega It looks like Jest keeps failing (I tried rerunning it too). Could you check and see if it's related to these changes?

Oops, thanks for catching that I forgot to rerun them at the end. I went ahead and fixed them in [136264d](https://github.com/CBIIT/crdc-datahub-ui/pull/557/commits/136264dc77f28cbbfbb2cde68dfb3eb5f0b22bdb).

Also FYI, I did find one additional issue on the BE for Data File related errors. Their codes are returning null, but the Metadata related error codes are populated correctly.

2025-01-16 15:37 UTC, amattu2 approved these changes
All the changes still LGTM and it seems to work as expected. 

---

I annotated a suggestion to skip the queries for the hidden filters when viewing aggregated view, which saves 3 network requests initially. The only downside is, when you toggle between aggregated/expanded, it will re-execute the queries every time instead of just once on mount (current implementation). 

I'm unsure if it's worth the tradeoff, since I don't know how often people will switch between the views. With that being said, I'll defer to you for the decision on this.

2025-01-16 15:37 UTC, amattu2 commented on src/components/DataSubmissions/QualityControlFilters.tsx
> +    skip: !submissionID,
```suggestion
    skip: !submissionID || isAggregated,
```

2025-01-16 15:37 UTC, amattu2 commented on src/components/DataSubmissions/QualityControlFilters.tsx
> +    skip: !submissionID,
```suggestion
    skip: !submissionID || isAggregated,
```

2025-01-16 15:37 UTC, amattu2 commented on src/components/DataSubmissions/QualityControlFilters.tsx
> +      skip: !submissionID,
```suggestion
      skip: !submissionID || isAggregated,
```

2025-01-16 16:22 UTC, Alejandro-Vega commented on src/components/DataSubmissions/QualityControlFilters.tsx
> +    skip: !submissionID,
Updated in [8581bdb](https://github.com/CBIIT/crdc-datahub-ui/pull/557/commits/8581bdb65d16b6038642b3ace8ff322aee3d4ee6).

2025-01-16 16:23 UTC, Alejandro-Vega commented on src/components/DataSubmissions/QualityControlFilters.tsx
> +    skip: !submissionID,
Updated in [8581bdb](https://github.com/CBIIT/crdc-datahub-ui/pull/557/commits/8581bdb65d16b6038642b3ace8ff322aee3d4ee6).

2025-01-16 16:23 UTC, Alejandro-Vega commented on src/components/DataSubmissions/QualityControlFilters.tsx
> +      skip: !submissionID,
Updated in [8581bdb](https://github.com/CBIIT/crdc-datahub-ui/pull/557/commits/8581bdb65d16b6038642b3ace8ff322aee3d4ee6).

2025-01-16 17:17 UTC, amattu2 approved these changes

2025-01-16 17:18 UTC, merged